In [1]:
from HiddenMarkovModel.hmmLearnAlgorithm import idealPrediction, predictAndScore, predictNext, averagePredictions
from HiddenMarkovModel.splitData import splitSet, formatData
import numpy as np
import os

In [2]:
lengths = []
print(os.getcwd())
print(os.listdir())

d:\Git\TestA\AE2224-I-B04
['.git', '.gitattributes', '.gitignore', 'BayesianDeepLearning', 'DataSets', 'DeepNN', 'HiddenMarkovModel', 'hmmNotebook.ipynb', 'README.md', 'SMOTE', 'utils']


In [3]:
splitSet("HMM_train_data.csv", 0.1)
observations, lengths = formatData("HMM_training_set.csv")
squishedObservations = np.concatenate(observations)

Validation set length: 460
Training set length: 4137


In [4]:
valObservations, valOutcomes = formatData("HMM_validation_set.csv", validation=True)

In [5]:
model1 = idealPrediction(squishedObservations, lengths, 30)

Converged 50: True		Score: -17101.547340590627
Converged 51: True		Score: -16768.358740905616
Converged 52: True		Score: -5047.307745856697
Converged 53: True		Score: -17101.469516668618
Converged 54: True		Score: -17101.50164910641
Converged 55: True		Score: -17100.76116151354
Converged 56: True		Score: -17101.185566310753
Converged 57: True		Score: -17100.944151830663
Converged 58: True		Score: -17101.81703894448
Converged 59: True		Score: -17100.17840286365
Converged 60: True		Score: -5047.307732181475
Converged 61: True		Score: -5047.30784555908
Converged 62: True		Score: -5047.307786529322
Converged 63: True		Score: -17100.865413226733
Converged 64: True		Score: -5047.307749207283
Converged 65: True		Score: -5047.308065613503
Converged 66: True		Score: -17101.817297566788
Converged 67: True		Score: -17101.82828509344
Converged 68: True		Score: -12854.630341641416
Converged 69: True		Score: -5047.314280513006
The best model had a score of -5047.307732181475


In [6]:
numNotZero = 0
for observation in observations:
    prediction = averagePredictions(model1, observation, 5, 5)
    if prediction.sum() > 0 : 
        print(prediction)
        numNotZero += 1

numNotZero

[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 0 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 0 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1

149

In [15]:
predictions, nextScore, lastScore = predictAndScore(model1, valObservations, valOutcomes, steps = 3, score = True)
nextScore, lastScore

Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next prediction: [0 0 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next prediction: [0 0 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next prediction: [0 0 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next prediction: [0 0 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next prediction: [0 0 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next prediction: [0 0 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next prediction: [0 0 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next prediction: [0 0 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1]
next prediction: [1 1 1]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next prediction: [0 0 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next prediction: [0 0 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next prediction: [0 0 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next prediction: [0 0 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next prediction: [0 0 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
next 

(99.1304347826087, 98.26086956521739)

In [ ]:
future, nonBinary = predictAndScore(model1, valObservations, valOutcomes, steps = 3, score = False )

display(future)
display(nonBinary)

ValueError: Expected 2D array, got 1D array instead:
array=[0].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.